// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/repo.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	algorithm "github.com/ozonva/ova-algorithm-api/internal/algorithm"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddAlgorithms mocks base method.
func (m *MockRepo) AddAlgorithms(algorithm []algorithm.Algorithm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAlgorithms", algorithm)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAlgorithms indicates an expected call of AddAlgorithms.
func (mr *MockRepoMockRecorder) AddAlgorithms(algorithm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAlgorithms", reflect.TypeOf((*MockRepo)(nil).AddAlgorithms), algorithm)
}

// DescribeAlgorithm mocks base method.
func (m *MockRepo) DescribeAlgorithm(algorithmID uint64) (*algorithm.Algorithm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAlgorithm", algorithmID)
	ret0, _ := ret[0].(*algorithm.Algorithm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAlgorithm indicates an expected call of DescribeAlgorithm.
func (mr *MockRepoMockRecorder) DescribeAlgorithm(algorithmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAlgorithm", reflect.TypeOf((*MockRepo)(nil).DescribeAlgorithm), algorithmID)
}

// ListAlgorithms mocks base method.
func (m *MockRepo) ListAlgorithms(limit, offset uint64) ([]algorithm.Algorithm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlgorithms", limit, offset)
	ret0, _ := ret[0].([]algorithm.Algorithm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlgorithms indicates an expected call of ListAlgorithms.
func (mr *MockRepoMockRecorder) ListAlgorithms(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlgorithms", reflect.TypeOf((*MockRepo)(nil).ListAlgorithms), limit, offset)
}
