version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - /home/melkozer/psqldata:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
